"""Stub file for custom_components/reflex_assistant_ui/assistant_ui.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any

import reflex as rx
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

__all__ = [
    "AssistantModal",
    "AssistantProvider",
    "AssistantThread",
    "ThreadList",
    "chat",
    "floating_chat",
    "modal",
    "provider",
    "thread",
    "thread_list",
]
_ASSISTANT_UI = "@assistant-ui/react@0.15.19"
_ASSISTANT_UI_MARKDOWN = "@assistant-ui/react-markdown@0.14.15"
_REMARK_GFM = "remark-gfm@4.0.1"
_SYNTAX_HIGHLIGHTER = "react-syntax-highlighter@16.1.1"
_BRIDGE = rx.asset("assistant_ui_bridge.jsx", shared=True)
_STYLESHEET = rx.asset("assistant_ui.css", shared=True)

class _AssistantUIBase(rx.Component):
    def add_imports(self) -> rx.ImportDict: ...
    @classmethod
    def create(
        cls,
        *children,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> _AssistantUIBase:
        """Create the component.

        Args:
            *children: The children of the component.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class AssistantProvider(_AssistantUIBase):
    @classmethod
    def create(
        cls,
        *children,
        messages: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        head_id: Var[str] | str | None = None,
        is_running: Var[bool] | bool | None = None,
        is_disabled: Var[bool] | bool | None = None,
        is_send_disabled: Var[bool] | bool | None = None,
        is_loading: Var[bool] | bool | None = None,
        suggestions: Var[list[Any]] | list[Any] | None = None,
        thread_list: Var[dict[str, Any]] | dict[str, Any] | None = None,
        attachments: Var[str] | str | None = None,
        enable_branching: Var[bool] | bool | None = None,
        enable_feedback: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_add_tool_result: EventType[()] | EventType[dict] | None = None,
        on_archive_thread: EventType[()] | EventType[str] | None = None,
        on_blur: EventType[()] | None = None,
        on_branch_change: EventType[()] | EventType[dict] | None = None,
        on_cancel: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_delete: EventType[()] | EventType[str] | None = None,
        on_delete_thread: EventType[()] | EventType[str] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_edit: EventType[()] | EventType[dict] | None = None,
        on_feedback: EventType[()] | EventType[dict] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_new: EventType[()] | EventType[dict] | None = None,
        on_reload: EventType[()] | EventType[rx.Var[str]] | None = None,
        on_rename_thread: EventType[()]
        | EventType[rx.Var[str]]
        | EventType[rx.Var[str], rx.Var[str]]
        | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_switch_to_new_thread: EventType[()] | None = None,
        on_switch_to_thread: EventType[()] | EventType[str] | None = None,
        on_unarchive_thread: EventType[()] | EventType[str] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> AssistantProvider:
        """Create the component.

        Args:
            *children: The children of the component.
            messages: The conversation, oldest first. Each entry is a dict with at least ``role`` and ``content``; ``id`` and ``parent_id`` enable branching.
            head_id: Id of the message at the tip of the visible branch. Defaults to the last message when omitted.
            is_running: Whether a response is being generated. Drives the stop button and the typing indicator.
            is_disabled: Disables the whole thread, composer included.
            is_send_disabled: Keeps the composer usable but blocks sending.
            is_loading: Shows the thread-loading state.
            suggestions: Follow-up suggestions offered after a reply. Strings, or dicts with ``prompt``/``title``/``label``.
            thread_list: Multi-conversation support: ``{"thread_id": ..., "threads": [...]}``.
            attachments: Attachment support: "none", "image", "text" or "all".
            enable_branching: Build a branchable message repository so edit/regenerate create branches instead of overwriting history.
            enable_feedback: Show thumbs up/down on assistant messages (requires ``on_feedback``).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_new: The user submitted a message. Receives the serialized message dict.
            on_edit: The user saved an edit of an earlier message.
            on_reload: The user asked to regenerate. Receives the parent message id.
            on_cancel: The user pressed stop.
            on_delete: The user deleted a message. Receives the message id.
            on_add_tool_result: A client-side tool produced a result.
            on_feedback: The user rated a message: ``{"message_id": ..., "type": "positive"}``.
            on_branch_change: The visible branch changed: ``{"head_id": ..., "visible_message_ids": [...]}``.
            on_switch_to_thread: Thread list: the user selected a conversation.
            on_switch_to_new_thread: Thread list: the user started a new conversation.
            on_rename_thread: Thread list: the user renamed a conversation.
            on_archive_thread: Thread list: the user archived a conversation.
            on_unarchive_thread: Thread list: the user unarchived a conversation.
            on_delete_thread: Thread list: the user deleted a conversation.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class AssistantThread(_AssistantUIBase):
    @classmethod
    def create(
        cls,
        *children,
        welcome_title: Var[str] | str | None = None,
        welcome_subtitle: Var[str] | str | None = None,
        welcome_suggestions: Var[list[Any]] | list[Any] | None = None,
        welcome_icon: Var[bool] | bool | None = None,
        placeholder: Var[str] | str | None = None,
        auto_focus: Var[bool] | bool | None = None,
        show_welcome: Var[bool] | bool | None = None,
        show_action_bar: Var[bool] | bool | None = None,
        show_branch_picker: Var[bool] | bool | None = None,
        show_feedback: Var[bool] | bool | None = None,
        show_avatar: Var[bool] | bool | None = None,
        show_attachments: Var[bool] | bool | None = None,
        show_follow_up_suggestions: Var[bool] | bool | None = None,
        submit_mode: Var[str] | str | None = None,
        max_width: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> AssistantThread:
        """Create the component.

        Args:
            *children: The children of the component.
            welcome_title: Heading shown while the thread is empty.
            welcome_subtitle: Secondary line under the heading.
            welcome_suggestions: Starter prompts on the empty state. Strings, or dicts with ``prompt``/``title``/``label``.
            welcome_icon: Show the sparkle badge above the welcome heading.
            placeholder: Composer placeholder.
            auto_focus: Focus the composer on mount.
            show_welcome: Render the empty state at all.
            show_action_bar: Copy / regenerate / edit buttons on messages.
            show_branch_picker: Branch navigation on messages that have siblings.
            show_feedback: Thumbs up/down (also needs ``enable_feedback`` on the provider).
            show_avatar: Assistant avatar next to each reply.
            show_attachments: Attachment button and drop zone (also needs ``attachments`` on the provider).
            show_follow_up_suggestions: Render follow-up suggestions above the composer.
            submit_mode: How Enter behaves: "enter", "ctrlEnter" or "none".
            max_width: Max width of the conversation column.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class ThreadList(_AssistantUIBase):
    @classmethod
    def create(
        cls,
        *children,
        new_thread_label: Var[str] | str | None = None,
        show_archive: Var[bool] | bool | None = None,
        show_delete: Var[bool] | bool | None = None,
        empty_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> ThreadList:
        """Create the component.

        Args:
            *children: The children of the component.
            new_thread_label: Label of the "new conversation" button.
            show_archive: Show the archive button on each row.
            show_delete: Show the delete button on each row.
            empty_label: Text shown when there are no conversations.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class AssistantModal(_AssistantUIBase):
    @classmethod
    def create(
        cls,
        *children,
        open_on_run_start: Var[bool] | bool | None = None,
        side: Var[str] | str | None = None,
        width: Var[str] | str | None = None,
        height: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> AssistantModal:
        """Create the component.

        Args:
            *children: The children of the component.
            open_on_run_start: Open the popover automatically when a run starts.
            side: Which corner to anchor to: "right" or "left".
            width: CSS width of the popover.
            height: CSS height of the popover.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

provider = AssistantProvider.create
thread = AssistantThread.create
thread_list = ThreadList.create
modal = AssistantModal.create
_THREAD_FIELDS = frozenset(AssistantThread.get_fields())
_PROVIDER_ONLY_FIELDS = frozenset(AssistantProvider.get_fields()) - _THREAD_FIELDS
_MODAL_ONLY_FIELDS = frozenset(AssistantModal.get_fields()) - _THREAD_FIELDS

def chat(**props: Any) -> rx.Component: ...
def floating_chat(**props: Any) -> rx.Component: ...
